export const styles = {
  loaderOverlayTransparent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backdropFilter: 'blur(5px)',
    zIndex: 9999,
    minHeight: '200px',
    backgroundColor: 'var(loader-theme-semilight-color-overlay)',
  },
  logoCenter: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%)',
  },
  logoWrapper: {
    width: '300px',
    height: '300px',
  },
  loaderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backdropFilter: 'blur(5px)',
    backgroundColor: 'var(loader-theme-white-color-overlay)',
    zIndex: 9999,
    minHeight: '200px',
  },
  loaderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backdropFilter: 'blur(5px)',
    backgroundColor: '$theme_white_color_overlay',
    minHeight: '200px',
  },
}
