import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "./../styles/Home.module.css";
import Link from "next/link";
import Search from "components/UseCase/HomePage/Search";
import BoxComponent from "components/Base/BoxComponent";
import SecondSection from "components/UseCase/HomePage/SecondSection";
import ThirdSecion from "components/UseCase/HomePage/ThirdSection";
import {
  relative_height_size_generator,
  relative_width_size_generator,
} from "utils/helpers";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Aqers App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BoxComponent sx={{ position: "relative" }}>
        <Search />
      </BoxComponent>
      <BoxComponent
        sx={{
          maxWidth: "1980px",
          "@media (min-width: 1600px)": {
            p: `${relative_height_size_generator(
              110
            )} ${relative_width_size_generator(
              243
            )} 0px ${relative_width_size_generator(243)}`,
          },
        }}
      >
        <SecondSection />
      </BoxComponent>
      <ThirdSecion />
    </>
  );
}
