import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "./../styles/Home.module.css";
import Link from "next/link";
import Search from "components/UseCase/HomePage/Search";
import BoxComponent from "components/Base/BoxComponent";
import HomePageSecondSection from "components/UseCase/HomePage/HomePageSecondSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <BoxComponent sx={{ p: "110 243 0 243" }}>
        <HomePageSecondSection />
      </BoxComponent>
    </>
  );
}
